server:
  port: 8001

spring:
  application:
    name: cloud-system-service # 入驻Eureka服务注册中心的服务名称

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据库的操作类型
    drives-class-name: com.mysql.cj.jdbc.Driver  # mysql 驱动包
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml  # sql 映射文件所在路径
  type-aliases-package: com.zjft.cloud.pojo # 实体类所在的包


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      defaultZone: http://localhost:7001/eureka # 入驻的服务注册中心地址


  instance:
    instance-id: system8001  # 实例别名
    prefer-ip-address: true # 访问路径可以显示 IP 地址